layout_spectrum: 0.8584332
typography_spectrum: 0.9262889
color:
  lightness: 0.8452846
  brandStrength: 0.5090614
  saturation: 0.4272293
  rhythmicContrast: 0.9446934
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: 'Hoffman Travel - NomadiChris '
